const API='';
const map=L.map('map',{zoomControl:false,preferCanvas:true,worldCopyJump:true}).setView([20,0],3);
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Esri World Imagery'}).addTo(map);
const labels=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Esri'}).addTo(map);
const streets=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});
const terrain=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{y}/{x}.png',{maxZoom:17,attribution:'© OpenTopoMap'});
L.control.zoom({position:'bottomright'}).addTo(map);
L.control.layers({Satellite:satellite,Street:streets,Terrain:terrain},{Labels:labels},{collapsed:true,position:'bottomright'}).addTo(map);
const $=id=>document.getElementById(id), search=$('search'), status=$('status'), coords=$('coords');
const layerDefs=[
 ['flights','✈','Flights'],['ships','⚓','Ships'],['public-transport','▣','Bus / Taxi / Rail / Metro / Ferry'],
 ['cameras','▤','Public Cameras'],['cells','⌁','Public Cells'],['infrastructure','◇','Infrastructure'],['road','●','Road Traffic']
];
const selected=new Set(['flights','ships','public-transport','cameras','cells']); const groups=new Map(); let lastData=null; let searchMarker=null; let gpsMarker=null; let sessionId=null; let watchId=null;
const layerList=$('layerList');
layerDefs.forEach(([id,icon,label])=>{const row=document.createElement('div');row.className='layerRow';row.innerHTML='<span>'+icon+' '+label+'</span><span class="switch '+(selected.has(id)?'on':'')+'" data-layer="'+id+'"></span>';layerList.appendChild(row)});
layerList.addEventListener('click',e=>{const s=e.target.closest('.switch');if(!s)return;const l=s.dataset.layer;if(selected.has(l)){selected.delete(l);s.classList.remove('on')}else{selected.add(l);s.classList.add('on')}loadMovement()});
function safe(v){return String(v??'—').replace(/[<>]/g,'')}
function icon(p){return ({flight:'✈',ship:'⚓',transit:'▣',camera:'▤',cell:'⌁',airport:'✈',train:'🚆',metro:'🚇',bus:'🚌',taxi:'🚕',ferry:'⛴'}[p.category]||'•')}
function logical(p){if(p.category==='flight')return'flights';if(p.category==='ship')return'ships';if(p.category==='camera')return'cameras';if(p.category==='cell')return'cells';if(p.category==='transit'||p.mode==='transit')return'public-transport';return selected.has('infrastructure')?'infrastructure':'road'}
function showObject(p,coords){$('objectCard').innerHTML='<div class="objectTitle"><h3>'+icon(p)+' '+safe(p.callsign||p.name||p.label||p.vehicle_id||p.category||'Object')+'</h3><span class="pill">'+safe(p.status||'LIVE')+'</span></div><div class="kv"><div><small>TYPE</small><span>'+safe(p.category||p.mode)+'</span></div><div><small>SOURCE</small><span>'+safe(p.source||'public feed')+'</span></div><div><small>POSITION</small><span>'+coords[1].toFixed(4)+', '+coords[0].toFixed(4)+'</span></div><div><small>UPDATED</small><span>'+safe(p.timestamp?new Date(Number(p.timestamp)*1000).toLocaleTimeString():p.last_contact?new Date(Number(p.last_contact)*1000).toLocaleTimeString():'source dependent')+'</span></div><div><small>SPEED</small><span>'+safe(p.velocity_mps!=null?(Number(p.velocity_mps)*1.944).toFixed(1)+' kt':p.speed_mps!=null?(Number(p.speed_mps)*3.6).toFixed(1)+' km/h':'—')+'</span></div><div><small>HEADING</small><span>'+safe(p.heading!=null?Math.round(p.heading)+'°':'—')+'</span></div></div><div class="source" style="margin-top:9px">TrackMeNow distinguishes live source data from estimated, static and historical information. No movement is fabricated.</div>'}
function clearGroups(){for(const g of groups.values())map.removeLayer(g);groups.clear()}
function drawFeatures(fc){clearGroups();const counts={flights:0,ships:0,'public-transport':0,cameras:0,cells:0};for(const f of fc.features||[]){const p=f.properties||{}, c=f.geometry?.coordinates;if(!c||c.length<2)continue;const l=logical(p);if(!selected.has(l))continue;counts[l]=(counts[l]||0)+1;let g=groups.get(l);if(!g){g=L.layerGroup().addTo(map);groups.set(l,g)}const m=L.circleMarker([c[1],c[0]],{radius:l==='flights'?5:4,weight:1,color:'#dcefff',fillColor:l==='flights'?'#43a8ff':l==='ships'?'#34d6c0':l==='public-transport'?'#ffca5c':'#d7e6f2',fillOpacity:.9});m.bindTooltip(icon(p)+' '+safe(p.callsign||p.name||p.label||p.vehicle_id||p.category),{direction:'top',opacity:.9});m.on('click',()=>showObject(p,c));m.addTo(g)}$('flightCount').textContent=counts.flights||0;$('shipCount').textContent=counts.ships||0;$('transportCount').textContent=counts['public-transport']||0;$('cameraCount').textContent=counts.cameras||0;return counts}
function renderSources(sources){$('feedHealth').innerHTML=(sources||[]).map(s=>'<div class="feedItem"><span class="dot" style="background:'+(s.status==='live'?'#35d49a':s.status==='error'?'#ff6672':'#f4bb55')+'"></span><b>'+safe(s.layer||'source')+'</b><br><span class="source">'+safe(s.source||'')+' · '+safe(s.status||'unknown')+(s.error?' · '+safe(s.error):'')+'</span></div>').join('')||'<div class="feedItem">No configured feed in current viewport.</div>'}
async function loadMovement(){const b=map.getBounds(),bbox=[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()].join(',');status.innerHTML='<span class="live">●</span> REFRESHING GLOBAL SOURCES…';try{const r=await fetch(API+'/api/global/movement?bbox='+encodeURIComponent(bbox)+'&layers='+encodeURIComponent([...selected].join(',')));if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();lastData=data;drawFeatures(data);renderSources(data.sources);const live=(data.sources||[]).filter(s=>s.status==='live').length;status.innerHTML='<span class="live">●</span> '+live+' LIVE SOURCES · '+new Date().toLocaleTimeString();coords.textContent='ZOOM '+map.getZoom()+' · '+map.getCenter().lat.toFixed(2)+', '+map.getCenter().lng.toFixed(2)}catch(e){status.innerHTML='<span style="color:#ff6672">●</span> SOURCE ERROR · '+safe(e.message)}}
let timer;map.on('moveend',()=>{clearTimeout(timer);timer=setTimeout(loadMovement,300)});setInterval(loadMovement,30000);
$('searchBtn').onclick=searchPlace;search.addEventListener('keydown',e=>{if(e.key==='Enter')searchPlace()});
async function searchPlace(){const q=search.value.trim();if(!q)return;const c=q.match(/^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$/);if(c)return flyTo(+c[1],+c[2],'Coordinates');try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+encodeURIComponent(q));const d=await r.json();if(!d[0])throw Error('No place found');flyTo(+d[0].lat,+d[0].lon,d[0].display_name)}catch(e){alert(e.message)}}
function flyTo(lat,lon,label){map.setView([lat,lon],15,{animate:true});if(searchMarker)map.removeLayer(searchMarker);searchMarker=L.marker([lat,lon]).addTo(map).bindPopup('<b>'+safe(label)+'</b>').openPopup();loadMovement()}
document.querySelectorAll('.nav[data-view]').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');const v=n.dataset.view;const mapLayers={air:['flights'],sea:['ships'],transport:['public-transport'],cameras:['cameras'],infra:['infrastructure','cells'],events:['road'],space:[]};if(mapLayers[v]){selected.clear();document.querySelectorAll('.switch').forEach(s=>s.classList.remove('on'));for(const l of mapLayers[v]){selected.add(l);document.querySelector('.switch[data-layer="'+l+'"]')?.classList.add('on')}loadMovement()}});
$('gpsBtn').onclick=async()=>{if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;$('gpsBtn').textContent='◎ GPS';status.innerHTML='<span class="live">●</span> GPS STOPPED';return}if(!navigator.geolocation)return alert('Browser GPS is unavailable.');try{const r=await fetch('/api/sessions',{method:'POST'});sessionId=(await r.json()).id}catch(e){return alert('Could not start GPS session.')}watchId=navigator.geolocation.watchPosition(p=>{const c=[p.coords.latitude,p.coords.longitude];if(!gpsMarker)gpsMarker=L.marker(c).addTo(map).bindPopup('AUTHORIZED LIVE GPS').openPopup();else gpsMarker.setLatLng(c);map.setView(c,Math.max(map.getZoom(),15));fetch('/api/sessions/'+sessionId+'/location',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lat:c[0],lon:c[1],accuracy:p.coords.accuracy,altitude:p.coords.altitude,heading:p.coords.heading,speed:p.coords.speed,timestamp:new Date(p.timestamp).toISOString()})});status.innerHTML='<span class="live">●</span> AUTHORIZED GPS · ±'+Math.round(p.coords.accuracy)+'m'},e=>status.textContent='GPS · '+e.message,{enableHighAccuracy:true,maximumAge:3000,timeout:15000});$('gpsBtn').textContent='Stop GPS'};
$('reportBtn').onclick=()=>{if(!lastData)return loadMovement().then(()=>showReport());showReport()};$('reportClose').onclick=()=>{$('report').classList.remove('show')};
function showReport(){const f=lastData?.features||[], c={};for(const x of f){const p=x.properties||{};const k=logical(p);c[k]=(c[k]||0)+1}$('reportGrid').innerHTML=[['Aircraft',c.flights||0],['Ships',c.ships||0],['Transport',c['public-transport']||0],['Cameras',c.cameras||0],['Cells',c.cells||0],['Infrastructure',c.infrastructure||0]].map(x=>'<div class="reportBlock"><b>'+x[0]+'</b><strong>'+x[1]+'</strong></div>').join('');$('reportSources').innerHTML=(lastData?.sources||[]).map(s=>'<div class="feedItem"><b>'+safe(s.layer)+'</b> · '+safe(s.status)+'<br><span class="source">'+safe(s.source)+'</span></div>').join('');$('report').classList.add('show')}
loadMovement();